[phases.setup]
nixPkgs = ["python310", "chromium", "chromedriver"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn backend_pro:app --host 0.0.0.0 --port $PORT"
